exports.seed = function (knex) {
  return knex('products')
    .del()
    .then(function () {
      return knex('products').insert([
        {
          id: 1,
          name: 'Ceramic pot',
          price: 50,
          color: 'Green',
          size: 'Small',
          status: 'in_stock',
          created_at: '2021-11-21 00:00:00',
          picture: 'src/client/assets/images/image01.png',
          stock_amount: 20,
          category_id: 3,
        },
        {
          id: 2,
          name: 'Table lamp',
          price: 150,
          color: 'White',
          size: 'Large',
          status: 'in_stock',
          created_at: '2021-12-01 00:00:00',
          picture: 'src/client/assets/images/image02.png',
          stock_amount: 58,
          category_id: 2,
        },
        {
          id: 3,
          name: 'Ceramic pottery',
          price: 120,
          color: 'Blue',
          size: 'Medium',
          status: 'running_low',
          created_at: '2021-12-02 00:00:00',
          picture: 'src/client/assets/images/image03.png',
          stock_amount: 140,
          category_id: 3,
        },
        {
          id: 4,
          name: 'Picture frame',
          price: 80,
          color: 'White',
          size: 'Extra-Large',
          created_at: '2021-12-03 00:00:00',
          picture: 'src/client/assets/images/image04.png',
          stock_amount: 2,
          category_id: 3,
        },
        {
          id: 5,
          name: 'Pillow case',
          price: 65,
          color: 'White',
          size: 'Medium',
          status: 'in_stock',
          created_at: '2021-11-29 00:00:00',
          picture: 'src/client/assets/images/image05.png',
          stock_amount: 2,
          category_id: 4,
        },
        {
          id: 6,
          name: 'Knitted plaid',
          price: 80,
          color: 'Yellow',
          size: 'Small',
          status: 'running_low',
          created_at: '2021-12-05 00:00:00',
          picture: 'src/client/assets/images/image06.png',
          stock_amount: 134,
          category_id: 4,
        },
        {
          id: 7,
          name: 'Mirror diamonds',
          price: 520,
          color: 'Green',
          size: 'Medium',
          status: 'in_stock',
          created_at: '2021-11-28 00:00:00',
          picture: 'src/client/assets/images/image07.png',
          stock_amount: 12,
          category_id: 3,
        },
        {
          id: 8,
          name: 'Ceramic candliers',
          price: 150,
          color: 'Yellow',
          size: 'Large',
          status: 'running_low',
          created_at: '2021-12-07 00:00:00',
          picture: 'src/client/assets/images/image08.png',
          stock_amount: 321,
          category_id: 3,
        },
        {
          id: 9,
          name: 'Retro chair',
          price: 850,
          color: 'Blue',
          size: 'Small',
          status: 'in_stock',
          created_at: '2021-11-25 00:00:00',
          picture: 'src/client/assets/images/image09.png',
          stock_amount: 7,
          category_id: 1,
        },
        {
          id: 10,
          name: 'Modern table lamp',
          price: 430,
          color: 'Black',
          size: 'Medium',
          status: 'in_stock',
          created_at: '2021-12-10 00:00:00',
          picture: 'src/client/assets/images/image10.png',
          stock_amount: 12,
          category_id: 2,
        },
        {
          id: 11,
          name: 'Silk pillow case',
          price: 120,
          color: 'Black',
          size: 'Large',
          created_at: '2021-12-05 01:00:00',
          picture: 'src/client/assets/images/image11.png',
          stock_amount: 12,
          category_id: 3,
        },
        {
          id: 12,
          name: 'Modern dining table',
          price: 520,
          color: 'Blue',
          size: 'Medium',
          status: 'in_stock',
          created_at: '2021-11-22 00:00:00',
          picture: 'src/client/assets/images/image12.png',
          stock_amount: 12,
          category_id: 1,
        },
        {
          id: 13,
          name: 'Flowerpot table lamp',
          price: 610,
          color: 'Blue',
          size: 'Medium',
          status: 'out_of_stock',
          created_at: '2021-11-27 00:00:00',
          picture: 'src/client/assets/images/image13.png',
          stock_amount: 0,
          category_id: 2,
        },
        {
          id: 14,
          name: 'Dining table chair',
          price: 430,
          color: 'Black',
          size: 'Medium',
          status: 'out_of_stock',
          created_at: '2021-11-27 00:00:00',
          picture: 'src/client/assets/images/image14.png',
          stock_amount: 0,
          category_id: 1,
        },
      ]);
    });
};
