exports.seed = function (knex) {
  return knex('products')
    .del()
    .then(function () {
      return knex('products').insert([
        {
          id: 1,
          name: 'Ceramic pot',
          price: 50,
          color: 'Green',
          picture: 'src/client/assets/images/image01.png',
          stock_amount: 20,
          category_id: 3,
        },
        {
          id: 2,
          name: 'Table lamp',
          price: 150,
          color: 'White',
          picture: 'src/client/assets/images/image02.png',
          stock_amount: 58,
          category_id: 2,
        },
        {
          id: 3,
          name: 'Ceramic pottery',
          price: 120,
          color: 'Blue',
          picture: 'src/client/assets/images/image03.png',
          stock_amount: 140,
          category_id: 3,
        },
        {
          id: 4,
          name: 'Picture frame',
          price: 80,
          color: 'White',
          picture: 'src/client/assets/images/image04.png',
          stock_amount: 2,
          category_id: 3,
        },
        {
          id: 5,
          name: 'Pillow case',
          price: 65,
          color: 'White',
          picture: 'src/client/assets/images/image05.png',
          stock_amount: 2,
          category_id: 4,
        },
        {
          id: 6,
          name: 'Knitted plaid',
          price: 80,
          color: 'Yellow',
          picture: 'src/client/assets/images/image06.png',
          stock_amount: 134,
          category_id: 4,
        },
        {
          id: 7,
          name: 'Mirror diamonds',
          price: 520,
          color: 'Green',
          picture: 'src/client/assets/images/image07.png',
          stock_amount: 12,
          category_id: 3,
        },
        {
          id: 8,
          name: 'Ceramic candliers',
          price: 150,
          color: 'Yellow',
          picture: 'src/client/assets/images/image08.png',
          stock_amount: 321,
          category_id: 3,
        },
        {
          id: 9,
          name: 'Retro chair',
          price: 850,
          color: 'Blue',
          picture: 'src/client/assets/images/image09.png',
          stock_amount: 7,
          category_id: 1,
        },
        {
          id: 10,
          name: 'Modern table lamp',
          price: 430,
          color: 'Black',
          picture: 'src/client/assets/images/image10.png',
          stock_amount: 12,
          category_id: 2,
        },
        {
          id: 11,
          name: 'Silk pillow case',
          price: 120,
          color: 'Black',
          picture: 'src/client/assets/images/image11.png',
          stock_amount: 12,
          category_id: 3,
        },
        {
          id: 12,
          name: 'Modern dinig table',
          price: 520,
          color: 'Blue',
          picture: 'src/client/assets/images/image12.png',
          stock_amount: 12,
          category_id: 1,
        },
      ]);
    });
};
